---
title: "A few of my favorites..."
---
I enjoy finding and sharing with others helpful resources and interesting reads. Below are a few of my favorite resources and readings. 

## Bookshelf
I am currently (or at least was when this page was last updated) reading the following books:

* _Info we Trust_ by R.J. Andrews
* _The Address Book_ by Deirdre Mask
* _The Lion, the Witch, and the Wardrobe_ by C.S. Lewis (reading with my kids)

I have read the following books and would recommend if you are looking for something new to read. You will find a variety of topics although most have some connection to data, statistics, or mathematics.

Math, Stat, and Data related:

* _Nabokov's Favorite Word is Mauve_ by Ben Blatt
* _The Ghost Map_ by Steven Johnson
* _Dear Data_ by Giorgia Lupi and Stefanie Posavec
* _The Tenth Muse_ by Catherine Chung

Miscellaneous topics:

* _Dirty Genes_ by Dr. Ben Lynch
* _The Last Lecture_ by Randy Pausch and Jeffery Zaslow
* _So what are you going to do with that?_ by Susan Basalla and Maggie Debelius
* _Juliet's School of Possibilities_ by Laura Vanderkam
