---
  title: "Research with Undergraduates"
---

I have directed and mentored several undergraduate research projects through the Grinnell College Mentored Advance Project (MAP) program. Working with undergraduate students is a rewarding experience. As exhibited below in the summaries and descriptions, I value providing students the opportunity to propose and cary out an individual direction of the team project. 

## Summer 2020: Survey Data Analysis and Methodology
This project explored data collected from the ACHA National College Health Assessment (NCHA). A team component focused on the demographic variables and examining how representative the sample seemed compared to the population. Each student then developed and pursued an independent direction. The goal was to explore ways this survey could be meaningfully utilized by an institution and to understand some of the nuances of working with survey data. This project was completed as an entirely virtual summer research experience. 

#### <span style="color: #38783f;"> **Danny Carter** (Class of 2022) </span>
Majors in History and Economics, Concentration in Statistics

>Danny established methodology for creating a student health index using a subset of the NCHA survey questions. This index assigns each respondent a score from 0 to 100 with higher numbers signaling the individual may be closer to optimal health and they practice healthy behaviors and lower scores may indicate the individual's overall health may be impacted negatively by health conditions and less healthy behaviors. In addition to presenting the index methodology, Danny also explored examples of how the index could be used by an institution through numerical and graphical methods.

#### <span style="color: #38783f;"> **Aru Fatehpuria** (Class of 2021) </span>
Majors in Mathematics and Psychology

>Aru examined the construction of survey weights for the Grinnell College NCHA dataset. The aims of the project were to (1) identify and select weighting variables and (2) compare and anlayze raking and post-stratification weighting menthods to select a reasonable weightig technique for this data. Innovative visualizations provided key insights into both components of the project. This work contributes to the conversation of how an institution can meaningfully use data collected through sub-optimal sampling to understand their student body in order to make data-supported decisions about student health policy and programming.    

Fatehpuria, Aru; “The great weight debate: Constructing, exploring, and visualizing survey weights to enhance representativeness and obtain population-level estimates from NCHA-II data,” Electronic Undergraduate Statistics Research Conference, November 6, 2020. https://www.causeweb.org/usproc/eusrc/2020/virtual-posters/7

#### <span style="color: #38783f;"> **Kexin (Cindy) Luo** (Class of 2021) </span>
Majors in Mathematics and Psychology

> Cindy conducted an Exploratory factor Analysis on the full Grinnell College NCHA dataset. The goal of this project was to detect the latent variables that underly Grinnell College students' health behaviors. The findings of this analysis can help to understand the structure of the instrument and be compared with findings from related studies. The analysis suggested 28 factors that explain 45% of the overall variance. Visualizations were created to aid in understanding the factor structure 

### Fall 2017: Digital History of World War II in the U.S.
The project was a collaboration between a student with a background in history and a student with a background in statistics. The project's goal was to study the Holocaust and japanese internment camps (during World War II) from the perspective of the median in the United States both through a standard historical analysis and natural language processing. This project was co-advised with Dr. Michael Guenther in the History Department at Grinnell College. Jun Taek Lee was the student I co-advised;  Alexander Chang (class of 2018) was the historian student on this project. 

#### <span style="color: #38783f;"> **Jun Taek Lee** (Class of 2018) </span>
Majors in Mathematics and Psychology, Concentration in Statistics

>Jun Taek worked with a large corpus of new articles (2,715,691) from four newspaper sources spaning the years 1938 to 1947. The raw text data was messy and needed substantial cleaning and processing prior to analysis. The skip-gram model of the word2vec algorithm converted text into numerical vectors and keywords were examined realted to the topic of the Holocaust and Japanese internment camps. Results from the machine learning approach were then discussed with the historian to determine whether they would provide any useful insights. Unfortunately there were many nonsensible results, most likely due to poor quality text data. 

The inter-disciplinary collaboration on this research project was documented through a [blog](https://fellers.sites.grinnell.edu/)

### Summer 2017: Text Analysis
The goals of this project were to advance the students' knowledge and skills of working with data by challenging them with unstructured data in the form of Text data. This was an exploratory project that dove into the area of text analysis, a topic that was not part of any current curriculum. Together we learned about a variety of methods and techniques for extracting, working with, and visualizing data from text and then each student proposed an independent project to develop an in-depth understanding of the method and application. 

#### <span style="color: #38783f;"> **Maggie Remus** (Class of 2018) </span>
Major in Economics, Concentration in Statistics

>Maggie focused her independent protion of the project on sentiment analysis. In particular, she was interested in applying sentiment analysis methods to understand podcasts. Transcripts of podcasts are an intriguing form of text as they are the text form of an orally delivered piece. Maggie explored the application of a variety of sentiment analysis methods to the transcripts from the Serial Podcast. Her work demonstrated a unique quantitative and visual approach to analyzing podcasts.

Maggie shared hilights of her work through a contributed blog post  to the Grinnell College Data Analysis & Social Inquiry lab's blog: [Sentiment Analysis of a Podcast](https://dasil.sites.grinnell.edu/2017/08/sentiment-analysis-of-a-podcast/ )

#### <span style="color: #38783f;"> **Anshul Tambay** (Class of 2020) </span>
Majors in Economics and Mathematics

>Anshul proposed a project to extract information from Screenplays that could then be utilized in additional statistical analyses. Working with screenplays as data was found to be more complicated than initially anticipated. Anshul's project required use of his computer science background to first develop an algrithm to parse film screenplays into tiday data using methods learned about working with text data and the screenplay structure. His algorithm parses each line of the screenplay into tiday data and assigns each line its category (i.e. slugline, dialogue, camera direction, etc.) and any other meaningful information depending on the category (i.e. dialogues are assigned a speaker and a location). The resulting tidy data can then be utilized in subsequent analyses to understand either an individual screenplay or a corpus of screenplays. 


### Summer 2015: Interactive Visualization and Modeling of Large Datasets
Professor Kuiper invited me along to mentor students on a project to examine two data resources, the Global Terrorism Database and the National Center for Health Statistics. The goal of this work was towfold; 1) incorporate advanced visualization tools into the model-building process to better identify key patterns within these datasets and 2) create new interactive visualization tools that would better communicate these key patterns to the general population. In total there were 5 students working on this project, I primarily directed and mentored two studens working with the National Center for Health Statisitcs datasets. 

#### <span style="color: #38783f;"> **Ruby Barnard-Mayers** (Class of 2016) and **Karin Yndestad** (Class of 2017) </span>
>Ruby and Karin focused their project on understanding, visualizing, and communicating the importance of incorporating the weight variable(s) into the analysis when working with survey data. They created 5 different classroom activities with accompanying online visualizations to introduce basic techniques used in estimating and testing population paramters using weights. They also created two advanced supplements, one on the mathematical details of the Rao-Scott method and the other providing more details on types of weights, subsetting, strata, and clustering.   

The materials created are available on [Professor Shonda Kuiper's webpage](https://stat2labs.sites.grinnell.edu/weights.html). Ruby and Karin contributed posts to the DASIL blog on [Estimation](https://dasil.sites.grinnell.edu/2015/10/understanding-population-estimates-based-upon-stratified-random-samples/) and [Testing](https://dasil.sites.grinnell.edu/2015/11/testing-weighted-data/).

The work of this project was continued and was acknowledged in the following paper published in the Journal of Statistics Educaiton:
Fellers, Pamela S., Kuiper, S. “Introducing Undergraduates to Concepts of Survey Data Analysis.” Journal of Statistics Education 28, no. 1 (2020): 18-24. [Link](https://doi.org/10.1080/10691898.2020.1720552)


